### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by raulanatol** [evilgom/repoAnuario#14]
https://github.com/raulanatol/curso_git_ull_2016/wiki/Reglas-para-puntuar

**Comment by evilgom** [comment]
Nos hace falta saber un correo, por lo menos, de los dos compañeros que no hemos podido contactar, Daniel y cursoGitULL que no pudo venir ayer. Tenemos un grupo de Hangouts por el que nos estamos comunicando desde ayer. Contactar conmigo para añadirlos, mi correo esta publicado en mi perfil.

 Saludos.

**Comment by moiseslodeiro** [comment]
:+1: Más divertido

**Comment by ardielgr** [comment]
:+1 Mas divertido
:+1 Mas original

**Comment by ardielgr** [comment]
:+1: Mas divertido
:+1: Mas original

**Comment by franmorales86** [comment]
:+1: Más original
:+1: Más divertido

**Comment by jurses** [comment]
:+1: Más original

**Comment by evilgom** [comment]
:+1: @mpescador76

**Comment by yodra** [comment]
:+1: Más original

**Comment by infojuani** [comment]
:+1: Más original

**Comment by simonemarin** [comment]
:+1: Más divertido 
:+1: Más original

**Comment by Dacoher** [comment]
:+1: @evilgom
